// using Azure.AI.OpenAI;
using Azure.AI.OpenAI;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Responses;

namespace BestPracticesMcp.UpdateWorker;

internal static class AgentDefinitions
{
    public static AIAgent CreateUpdateAgent(AzureOpenAIClient openAIClient, UpdateAgentConfig config)
    {
        // Define the UpdateAgent which checks for updates to language documents
        AIAgent updateAgent = openAIClient
            .GetChatClient(config.DeploymentName)
            .AsIChatClient()
            .AsAIAgent(
                instructions: $"""
                    You are an expert at evaluating programming language best-practices documentation for accuracy and currency.

                    When invoked, use your tools to:
                    1. Parse the document's YAML frontmatter using ReadFrontmatter
                    2. Check all resource URLs for availability using CheckResourceUrls
                    3. Check the latest stable language version using CheckLatestVersion
                    4. If content has changed, compute and compare content hashes using CompareContentHash

                    CRITICAL RULES:
                    - Only consider GA/stable releases. IGNORE alpha, beta, RC, preview, dev, canary, and nightly versions.
                    - If no changes are detected and the document is current, return needsUpdate: false.
                    - If changes are detected, produce a COMPLETE updated markdown document preserving the existing
                    structure, sections, format conventions, and YAML frontmatter schema.
                    - Update the frontmatter with new language_version, today's date as last_checked, and new resource_hash.
                    - Do NOT add information about beta, preview, or prerelease features.
                    - Provide a changeSummary explaining what changed and why each modification was made.
                    - You may NOT trust your built-in knowledge to determine a language version. ALWAYS use the version_source_url and CheckLatestVersion tool to detect the latest stable version.

                    Return your response as a JSON object with fields:
                    languageName, needsUpdate, updatedContent, changeSummary, filePath
                    """,
                name: "LanguageUpdateAgent",
                tools: [.. config.Tools]);
        return updateAgent;
    }

    public static AIAgent CreateGithubAgent(AzureOpenAIClient openAIClient, GithubAgentConfig config)
    {

        AIAgent prAgent = openAIClient
            .GetChatClient(config.DeploymentName)
            .AsIChatClient()
            .AsAIAgent(
                instructions: $"""
                    You are a GitHub automation agent that creates pull requests for updated best-practices documents.

                    REPOSITORY CONTEXT:
                    - Owner: {config.RepoOwner}
                    - Repo: {config.RepoName}
                    - Default branch: {config.DefaultBranch}

                    When invoked, you will receive a JSON payload describing updated language documents.
                    Use your GitHub MCP tools to:

                    1. Create a new branch named "auto-update/YYYY-MM-DD" (using today's date) from the default branch "{config.DefaultBranch}"
                    using the create_branch tool with owner="{config.RepoOwner}", repo="{config.RepoName}".

                    2. Push all updated files in a single commit using the push_files tool.
                    Each file should use its repository-relative path (e.g. "Languages/Python/python-best-practices.md").
                    Use a commit message like "Auto-update <language> best practices" for single files,
                    or "Auto-update best practices for N languages" for multiple files.

                    3. Create a pull request using the create_pull_request tool with:
                    - owner: "{config.RepoOwner}"
                    - repo: "{config.RepoName}"
                    - title: "[Auto-Update] Best practices refresh — YYYY-MM-DD"
                    - head: the branch name you created
                    - base: "{config.DefaultBranch}"
                    - body: A markdown summary listing each language updated with its change summary.
                        End with: "---\n*This PR was automatically generated by the BestBot Update Worker.*"

                    Return a JSON object with fields: prUrl (the HTML URL of the created PR)
                    """,
                name: "PrCreationAgent",
                tools: [.. config.Tools]);

        return prAgent;
    }
}

internal sealed record UpdateAgentConfig(
    string DeploymentName,
    IList<AITool> Tools);

internal sealed record GithubAgentConfig(
    string DeploymentName,
    string RepoOwner,
    string RepoName,
    string DefaultBranch,
    IList<AITool> Tools);