name: CI Build and Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore BestPracticesMcp.sln

      - name: Build
        run: dotnet build BestPracticesMcp.sln --no-restore

      - name: Verify code formatting
        run: dotnet format BestPracticesMcp.sln --verify-no-changes

      - name: Publish (validation)
        run: dotnet publish BestPracticesMcp.sln --configuration Release --no-build